title       = "tumblr"
baseURL     = "https://tumblr-cli.tamnd.com/"
description = "A command line for tumblr."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/tumblr-cli"
